# Generated by Django 2.0.7 on 2018-07-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_auto_20180730_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('bp', models.CharField(max_length=20)),
                ('fh', models.CharField(max_length=20)),
                ('fht', models.CharField(max_length=20)),
                ('lmp', models.DateField()),
                ('edc', models.DateField()),
                ('aog', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=1000)),
                ('medication', models.CharField(max_length=1000)),
                ('return_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
