# Generated by Django 2.0.7 on 2018-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='aog',
            field=models.FloatField(),
        ),
    ]
